# 0 : door
# 1 : wall

int32 goal_type

# 0 : left
# 1 : front
# 2 : right

int32 direction
float32 distance

int32[] available_features
int32[] available_features_directions
float32[] available_features_distances
---
---
float32 distance_travelled
float32 current_direction
float32 desired_direction
bool recovery_mode